version: "2.6.1"

services:
  postgres_db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: database

  web:
    build:
      context: ./
      dockerfile: Dockerfile
    command: bash -c "python manage.py makemigrations &&
                      python manage.py migrate --noinput &&
                      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - os_data:/app
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - postgres_db
      - redis
    container_name: main

  redis:
    image: redis:5
    command: "redis-server"
    ports:
      - "6379:6379"
    container_name: redis
    volumes:
      - redis_data:/redis

volumes:
  postgres_data:
  os_data:
  redis_data:
